config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :todos do
    resources :fields
    resources :items
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "todos#index"
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  broadcasts_to :todo

  belongs_to :todo, inverse_of: :items, optional: false

  has_many :field_associations, as: :target, inverse_of: :target, dependent: :destroy
  has_many :fields, through: :field_associations, source: :field

  validates :name, presence: true

  accepts_nested_attributes_for :field_associations, allow_destroy: true, reject_if: :reject_field_associations

  def reject_field_associations(_attributes)
    false
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :set_todo

  before_action :set_item, only: %i[destroy]

  # GET /items/new
  def new
    @item = @todo.items.new
    @todo.fields.each do |field|
      @item.field_associations.build(field:)
    end
  end

  # POST /items or /items.json
  def create
    @item = @todo.items.new(item_params)

    @collections = Collections.new(@todo)
    @filter      = Memoization.new(@todo, {})

    @filter.name ||= Obfuscator.new.encrypt({ name: @todo.items.first.name }.to_json) if @todo.items.any?

    respond_to do |format|
      if @item.save

        position = 0
        field_params.each do |key, value|
          @item.field_associations.create(
            field: @todo.fields.where(identifier: key).take,
            position: position += 1,
            value:
          )
        end

        format.html { redirect_to todo_item_url(@todo, @item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
        format.turbo_stream { flash.now[:notice] = "Item was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to todo_items_url(@todo), notice: "Item was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream do
        flash.now[:notice] = "Item was successfully destroyed."
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = @todo.items.find(params[:id])
  end

  def set_todo
    @todo = Todo.find(params[:todo_id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:name, field_associations_attributes: %i[id field_id value _destroy])
  end

  def field_params
    params.require(:fields).permit(*@todo.fields.pluck(:name).map(&:downcase).map(&:to_sym))
  rescue ActionController::ParameterMissing
    {}
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: [@todo, item], data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }, class: "contents") do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, "Item Name" %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <% item.todo.fields.each do |field| %>
    <% field_association = item.field_associations.where(field: field).take %>
    <% field_association ||= item.field_associations.build(field: field)%>
    <%= form.fields_for field_association, class: "contents" do |field_association_subform| %>
      <div class="my-5">
        <%= field_association_subform.label :value, (field_association_subform.object.field ? field_association_subform.object.field.name : "Unknown") %>
        <%= field_association_subform.text_field :value, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        <% if field_association_subform.object.field %>
          <%= field_association_subform.text_field :field_id, class: field_association_subform.object.field.id, hidden: true %>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>" class="item rounded-lg my-5 py-3 px-5 bg-gray-100">
  <div class="flex flex-row justify-between">
    <div class="font-medium text-slate-800">
      <%= item.name %>
    </div>
    <%=
      link_to(
        'Destroy this item',
        todo_item_path(item.todo, item),
        data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        },
        class: "rounded-lg font-medium"
      )
    %>
  </div>

  <% item.field_associations.each do |field_association| %>
    <div class="flex flex-row justify-between">
      <div class="font-sm text-slate-800">
        <%= field_association.field.name %>
      </div>
      <div class="font-sm text-slate-800">
        <%= field_association.value %>
      </div>
    </div>
  <% end %>

</div>

app/views/items/create.turbo_stream.erb
<%= turbo_stream.replace target="flash", partial: "layouts/flash" %>

<%= turbo_stream.replace target="filter" do %>
  <%= content_tag :div, id: "filter" do %>
    <%= render partial: "todos/filter", locals: { filter: @filter, todo: @todo, collections: @collections } %>
  <% end %>
<% end %>

app/views/items/destroy.turbo_stream.erb
<%= turbo_stream.remove(dom_id(@item)) %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/items/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New item</h1>

  <%= turbo_frame_tag "new_item" do %>
    <div class="rounded-lg py-3 px-5 bg-gray-100">
      <%= render "form", item: @item %>
    </div>
  <% end %>

  <%= link_to 'Back to items', todo_items_path(@todo), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>