config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :todos do
    resources :fields
    resources :items
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "todos#index"
end

app/models/todo.rb
# frozen_string_literal: true

class Todo < ApplicationRecord
  has_many :items, inverse_of: :todo, dependent: :destroy

  has_many :fields, as: :source, inverse_of: :source, dependent: :destroy
  has_many :settings, inverse_of: :todo, dependent: :destroy

  validates :name, presence: true

  accepts_nested_attributes_for :settings, allow_destroy: true, reject_if: :reject_settings

  def reject_settings(_attributes)
    false
  end

  # def settings_attributes=(attributes)
  #   super
  # end

  def custom_fields
    fields.pluck(:identifier).map(&:to_sym)
  end

  def filterable_fields
    [:name, *fields.map(&:predicate).map(&:to_sym)]
  end
end

app/controllers/todos_controller.rb
# frozen_string_literal: true

class TodosController < ApplicationController
  include Filtering
  include Paginate

  before_action :set_todo, only: %i[show edit update destroy]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
    @collections = Collections.new(@todo)
    @filter      = Memoization.new(@todo, filter_params)

    @filter.name ||= Obfuscator.new.encrypt({ name: @todo.items.first.name }.to_json) if @todo.items.any?

    filter(@todo.items, @filter.constraints) do |filtered|
      paginate(filtered) do |paginated|
        @filtered_items = paginated
      end
    end
  end

  # GET /todos/new
  def new
    @todo = Todo.new
    @todo.settings.build(name: "foo")
  end

  # GET /todos/1/edit
  def edit
    @todo.settings.build(name: "foo")
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_todo
    @todo = Todo.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def todo_params
    params.require(:todo).permit(:name, settings_attributes: %i[id name _destroy])
  end

  def filter_params
    return {} unless params.key?(:filter)

    params.require(:filter).permit(*@todo.filterable_fields)
  end
end

app/helpers/todos_helper.rb
# frozen_string_literal: true

module TodosHelper
end

app/views/todos/_filter.html.erb
<div class="rounded-lg py-3 px-5 bg-gray-100">

  <%= form_for :filter, method: :get do |f| %>

    <div class="flex flex-row justify-between">
      <%= f.label :name, "Name", class: "font-small" %>
      <%= f.select :name, collections.names, options = {}, html_options = { class: "rounded-lg px-5 bg-gray-100 font-small" } %>
    </div>

    <% todo.fields.each do |field| %>
      <div class="flex flex-row justify-between">
        <%= f.label field.predicate, field.name, class: "font-small" %>
        <%= f.select field.predicate, collections.public_send(field.collection_name), options = {}, html_options = { class: "mt-2 rounded-lg px-5 bg-gray-100" }  %>
      </div>
    <% end %>

    <div class="flex justify-end">
      <%= submit_tag "Apply", class: "rounded-lg py-3 bg-gray-100 font-small hover:bg-black" %>
    </div>

  <% end %>

</div>

app/views/todos/_form.html.erb
<%= form_with(model: todo, class: "contents") do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= label_tag :todo_name, "Todo" %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%= form.fields_for :settings, class: "contents" do |setting_subform| %>
    <div class="my-5">
      <%= setting_subform.label :name, "Setting" %>
      <%= setting_subform.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= setting_subform.check_box :_destroy %>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>" class="rounded-lg my-5 py-3 px-5 bg-gray-100">
  <p>
    <%= todo.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this todo", todo, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this todo', edit_todo_path(todo), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/todos/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing todo</h1>

  <%= render "form", todo: @todo %>

  <%= link_to "Show this todo", @todo, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to todos", todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/todos/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Todos</h1>
    <%= link_to 'New todo', new_todo_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="todos" class="min-w-full">
    <%= render @todos %>
  </div>
</div>

app/views/todos/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New todo</h1>

  <%= render "form", todo: @todo %>

  <%= link_to 'Back to todos', todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/todos/show.html.erb
<%= turbo_stream_from @todo %>

<div class="mx-auto">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <%= content_tag :div, id: "filter" do %>
    <%= render partial: "filter", locals: { filter: @filter, todo: @todo, collections: @collections } %>
  <% end %>

  <%= render @todo %>

  <%= content_tag :div, id: "items" do %>
    <%= render @filtered_items %>
  <% end %>

  <%= turbo_frame_tag "new_item", src: new_todo_item_path(@todo) %>

  <%= content_tag :div, id: "fields", class: "my-5 rounded-lg py-3 px-5 bg-gray-100" do %>
    <strong class="block font-medium mb-1">Custom Fields:</strong>
    <%= render @todo.fields %>
  <% end %>

  <div class="rounded-lg py-3 px-5 bg-gray-100">
    <%= turbo_frame_tag "new_field", src: new_todo_field_path(@todo) %>
  </div>

  <%= link_to 'Edit this todo', edit_todo_path(@todo), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to 'Destroy this todo', todo_path(@todo), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
  </div>
  <%= link_to 'Back to todos', todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>